### ISSUE TITLE
Incorrect badges

### ISSUE THREAD

**Issue by richardschneider** [libp2p/js-libp2p-keychain#11]
The build and coverage badges are wrong.
![badges](https://user-images.githubusercontent.com/631061/33793805-67b0137c-dd23-11e7-9f18-a9a7b336e363.png)

@diasdavid Any ideas on how to fix?

**Comment by diasdavid** [comment]
Seems that only Coveralls is missing, I've enabled it and it should change on next CI run

https://coveralls.io/github/libp2p/js-libp2p-keychain

<img width="979" alt="image" src="https://user-images.githubusercontent.com/1211152/33803822-aea0d83a-dd90-11e7-9760-cdd1cd6110d7.png">
