### ISSUE TITLE
Help with JSDoc

### ISSUE THREAD

**Issue by richardschneider** [libp2p/js-libp2p-keychain#14]
The below code does not generate any documentation on the KeyInfo properties.  I'm using `aegir docs` to build the documentation.

Any help would be greatly appreciated. 

 from https://github.com/libp2p/js-libp2p-keychain/blob/2dd069b05a0cd6b84bdb4c07b944a0d024c6758f/src/keychain.js#L91

```js
/**
 * Information about a key.
 *
 * @typedef {Object} KeyInfo
 *
 * @property {string} id - The universally unique key id.
 * @property {string} name - The local key name.
 */
```

**Comment by achingbrain** [comment]
This is fixed now as everything's generated from typescript instead of jsdoc: https://libp2p.github.io/js-libp2p-interfaces/interfaces/_libp2p_interface_keychain.KeyInfo.html
