### ISSUE TITLE
Any plans to upgrade 'datastore-*' deps?

### ISSUE THREAD

**Issue by laubsauger** [libp2p/js-libp2p-keychain#36]
Currently depending on `interface-datastore@0.6.0` and `datastore-level@10.0.0` which is a problem for node v12 users (at least on macOS) since it uses `leveldown@3.0.2` but would need `leveldown@5` to compile successfully.

Using `datastore-level` (and `interface-datastore`) at current versions get's around that issue but poses the problem that they switched to use Promises back in December 2018 which `js-libp2p-keychain` does not handle yet. 

Are there any plans to be compatible with these?

**Comment by vasco-santos** [comment]
Upgrading this is currently on my list. I need to check what is the state of its dependencies to understand if this is already unblocked

**Comment by vasco-santos** [comment]
@laubsauger it is done and released now! 🚢
