### ISSUE TITLE
version 5, used by js-ipfs, is missing "promisify-es6" module used in keychain.js

### ISSUE THREAD

**Issue by ruifortes** [libp2p/js-libp2p-keychain#41]
Hi.
js-ipfs is still using this modules v5 that has "promisify-es6" in devDependencies

**Comment by vasco-santos** [comment]
Hey @ruifortes 

Thanks for reporting this, just created a PR to fix it

**Comment by vasco-santos** [comment]
Released new `0.5.5` version
